### ISSUE TITLE
Communication of roadmap launch

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#102]
- [x] language review
- [x] add links to roadmap and user stories to homepage
- [x] add links to roadmap and user stories to websites
- [x] Open Hours
- [x] email to members
- [x] Blog post
- [x] Email Board
- [x] Email Services Steering Group
- [x] Readme in datacite/datacite repo

**Comment by mfenner** [comment]
Links to roadmap and user stories on DataCite service pages are tracked at datacite/datacite#126.
