### ISSUE TITLE
Use GitHub Actions for Continuous Integration

### ISSUE THREAD

**Issue by mfenner** [datacite/datacite#1181]
This issue is to track the upgrades from travis to github actions

Todo:

- [x] omniauth_globus
- [x] lupo (API/GraphQL)
- [x] bolognese
- [x] #1370 
- [x] #1373 
- [x] volpino (profiles)
- [x] #1369 
- [x] dackel (repository finder) (NOT DOING) as part of new repository search in commons, it's not worth moving.
- [ ] #1374 
- [x] vaestgoetaspets (Datacite GraphQL API Gateway)
- [-] cirneco (datacite cli) - Not doing due to it being CLI app, doesnt need a release. It also is a good target for retirement at some point as it's using MDS API.
- [x] poodle (mds)
- [x] content-negotiation
- [x] homepage
- [x] #1372 
- [x] sashimi
- [x] levriero
- [x] orcid_client

**Comment by richardhallett** [comment]
With the exception of spitz, this is complete.
I am going to close and treat spitz seperatly as it's not ugent and does not affect retiring of travis.
Everything key is now on github workflows
