### ISSUE TITLE
Setting up Plausible Analytics within the DataCite infrastructure (Suzanne)

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1231]
Run the <https://github.com/plausible/analytics> software within DataCite infrastructure for the Data Usage as a service pilot.

**Comment by sarala** [comment]
Link to subfeature: https://datacite.productboard.com/feature-board/planning/features/7239847

**Comment by svogt0511** [comment]
RESOURCES

- [DataCite Plausible Sites](https://plausible.io/sites)
- [Plausible on GitHub](https://github.com/plausible/analytics)
- [Plausible: Self-Hosted Google Analytics Alternative](https://plausible.io/self-hosted-web-analytics) 
- [Installation docs](https://plausible.io/docs/self-hosting)
- [Live Demo](https://plausible.io/plausible.io)
- [Plausible Forum](https://github.com/plausible/analytics/discussions)
- [ Linux Handbook: Plausible Deployment Guide](https://linuxhandbook.com/plausible-deployment-guide/)
- [MaxMind Documentation and API](https://dev.maxmind.com/?utm_source=txn_email&utm_medium=email&utm_campaign=account)

Some goals for adding the self-hosted plausible.io to the DataCite Infrastructure:

- [ ] Learning by getting it up and running in the local development environment.  
- [ ] New DataCite Github repository - terrier? Forked from plausible GitHub.  smtprelay@datacite.org
- [ ] Accounts:
  - Plausible.io Admin Account
  - Account and geolocation database from MaxMind.com.
  - Database Admin AccountS and instance (AWS - click house and PostgreSQL)
  - SMTP Mail server Account (which one?)
    - DataCite Google SMTP server? (smtprelay@datacite.org)
    - MailGun - the other DataCite mail server? (postmaster@mg.datacite.org)
- [ ] ECS/FARGATE container instances running the new docker container.
- [ ] Database Instances:
  - Postgres SQL - for user data
  - Clickhouse - for analytics data
- [ ] Amazon Route53 - domains/routing/load balancing/reverse proxy
  - plausible.datacite.org, 
  - plausible.stage.datacite.org, 
  - plausible.test.datacite.org.
- [ ] Terraform Configuration
  - Need a new terraform workspace.
  - Coded config in mastino with the following:
    - mastino files with the following (ECS, route53 (DNS, load balancer, etc), cloudwatch metrics, cloudwatch log group, service discovery):
    - services stage/test/production
    - dns plausible.datacite.org/plausible.test.datacite.org/plausible.stage.datacite.org
   - main.tf -  https://github.com/datacite/mastino/prod-eu-west/services/plausible/main.tf
        - s3bucket? - maybe later for deployment of stats in sashimi.
        - aws_ecs_service - “plausible"
            - launch_type - “FARGATE"
            - load_balancer - container name (plausible), ports (80, 443).
            - network_configuration -  ???
            - service_registries - ???
        - aws_appscaling… - ???
        - aws_cloudwatch_metric_alarm - ???
        - aws_lb_target_group - name (plausible), port (8000), protocol (http) vpc_id (???), target_type (???)
        - aws_lb_listener_rule - specifies action (forward), listener and target -  host_header (plausible.datacite.org), path_pattern (“/“)
        - aws_cloudwatch_log_group
        - aws_route53_record - name (dns “plausible.datacite.org”)
        - aws_service_discovery_service...
   - _plausible.auto.tfvars - https://github.com/datacite/mastino/services/prod-eu-west/plausible/_plausible.auto.tfvars 
        - sha and tag for versioning
        - *** need github actions for deployment
    - input.tf - https://github.com/datacite/mastino/services/prod-eu-west/plausible/input.tf 
        - provider
        - aws_route_53_zone
        - other variables, including some from vars.tf, specified in terraform.
    -  plausible.json - https://github.com/datacite/mastino/services/prod-eu-west/plausible.json 
       - other settings, name, image, cpu,memory, logconfig, environment variables.
    - terraform.tf - https://github.com/datacite/mastino/services/prod-eu-west/terraform.tf 
        - Ties terraform workspace for plausible to this provisioning.
    - var.tf - https://github.com/datacite/mastino/srvices/prod-eu-west/var.tf 
        - Makes terraform ui variables available to mastino.
     - github repo - terrier   https://github.com/datacite/mastino/global/github/repositories.tf  :
         -  example - what is this for? I don’t see sashimi. I thought this is where we would put the repository info.
 - [ ] Sentry or other monitoring?
 - [ ] Logging?
 - [ ] User accounts?  (Separate from other DataCite accounts.)
 - [ ] Standard scripts for tracking downloads and other items.  Currently only page views are tracked.
 - [ ] Other issues?
 - [ ] Development tools:
   - Postgres/clickhouse tools similar to mysqlworkbench?
   - How to effectively debug
   - How to add functionality.

**Comment by svogt0511** [comment]
Closing this.  Moved all issues to Epic [Usage Stats Processing as a Service [Capture and Processing]](https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/datacite/datacite/1347)
