### ISSUE TITLE
PoC Usage Stats Processing as a Service [Capture and Processing] (Richard)

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1347]
<p></p>

<p></p>

<p></p>

Product Spec: <https://docs.google.com/document/d/18NAwd8zYXwQea48IKGGYiepdE9l03wPKJtbFDqKYr9U/edit#>

Technical Spec: <https://docs.google.com/document/d/1qDFbzcYzXbIE0GZLIJ0LtWIeKAwFl3EYXN0OBStQW98/edit?usp=sharing>

Resources: <https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/datacite/datacite/1231>

**Scroll down to see resource list in [Zenhub Issue #1231](https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/datacite/datacite/1231)

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/8671827

**Comment by svogt0511** [comment]
There are several epics and a number of tasks that have been opened that need to be centralized here so we can track what progress has been made.  I am going through these and closing out the things that are done, and adding tasks here for things that are not done.

Starting with:

- https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/datacite/datacite/1306
- https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/datacite/datacite/1231

CURRENT STATUS:

- Everything I have done is in the staging environment only.
- Datacite has a running analytics site in the staging environment: [analytics.stage.datacite.org](https://analytics.stage.datacite.org)
- Fabrica allows an integrated dashboard for each repository that has analytics turned on.  For example: I have a sample repository [here](https://doi.stage.datacite.org/repositories/datacite.skv).  Click the 'Usage Dashboard' tab to see the dashboard.  It is integrated by adding a url in the 'update repository' screen in Fabrica.  If there is no dashboard url, it will report that there are no analytics for this repository.  
- Analytics reporting in Fabrica can be turned on/off by setting a flag in Vercel.

**Comment by kjgarza** [comment]
Completed user stories (checked) as of Dec 16th. 

- [ ] 1 Feature: Usage Stats Tracker Installation
  - [ ] 1.1 Scenario: Installing the Usage stats tracker correctly
- [ ] 2 Feature: Detecting DOI names in landing pages
  - [ ] 2.1 Scenario: DOI name is stated as an attribute in the tracking snippet
  - [ ] 2.2 Scenario: DOI name is not stated as an attribute in the tracking snippet
  - [ ] 2.3 Scenario: DOI name is not to be found anywhere
- [ ] 3. Feature: Usage Stats Processing Service
  - [ ] 3.2 Scenario: Receiving usage stats from the Tracker for non-Datacite DOIs (transfer or malformed)
  - [ ] 3.3. Scenario: DOI and URL do not match Handle registry
- [ ] 4 Feature: Accessing Usage Stats Processing
  - [ ] 4.1 Scenario: Displaying Usage Stats from Tracker in Fabrica

**Comment by svogt0511** [comment]
Finished user story 2.2 with functions derived from [pidcheck](https://github.com/datacite/pidcheck/blob/master/crawler/pidcheck/spiders/pid_spider.py) and [bolognese/doi_utils](https://github.com/datacite/bolognese/blob/0f3b1d1f3830399a24e69d0f2262e7ff7c0190c9/lib/bolognese/doi_utils.rb).

**Comment by kjgarza** [comment]
@svogt0511 Just keep in mind that to achieve the definition of "Easy to install" all scripts should be working by adding header tag (and events hooks in the case of downloads). No other installion must be needed. Take a look at the wireframe if that's not clear.

**Comment by svogt0511** [comment]
Working on making the script available from analytics.stage.datacite.org, the same as the standard scripts includable to make the analytics work.


Does that include not having to add an attribute to the download button?




Suzanne

--- original message ---
On December 17, 2021, 12:35 PM EST ***@***.*** wrote:



@svogt0511 Just keep in mind that to achieve the definition of "Easy to install" all scripts should be working by adding header tag (and events hooks in the case of downloads). No other installion must be needed. Take a look at the wireframe if that's not clear.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by kjgarza** [comment]
Well, the expectation is that by adding only the following they complete the installation:

![image](https://user-images.githubusercontent.com/1092861/146586045-9b574302-68f3-4265-9e08-2fd91172398d.png)

Would I be correct to assume that to "`add an attribute to the download`" would be the same as the custom Event hook? See the second line in the image. 


https://www.figma.com/proto/Fd54mIb3WVYqQfw3KQmp68/SAAS-Processor?node-id=2%3A0
