### ISSUE TITLE
Fabrica Improvements 2022 (SV/CR/BL)

### ISSUE THREAD

**Issue by sarala** [datacite/datacite#1428]
Implement a list of new Fabrica features.

<p></p>

**SP5: Adapting our processes and workflows to meet our members needs**

<p></p>

<https://www.iana.org/assignments/media-types/media-types.xhtml>

<p></p>

<p></p>

**Product Spec:** [**https://docs.google.com/document/d/1Tl6ctSaSG3487IMktlgfy8IZaMYVRTNzu5VObyqXCWY/edit#heading=h.37sflf1e0bm9**](https://docs.google.com/document/d/1Tl6ctSaSG3487IMktlgfy8IZaMYVRTNzu5VObyqXCWY/edit#heading=h.37sflf1e0bm9)

**Technical Spec:**
[Fabrica 4.0 Improvements Technical Spec - 2022](https://docs.google.com/document/d/1dstFR8KIPR3oHPoN9Yk9Y_80xg_y_njsDcCNtV1sIl4/edit?usp=sharing)

**Vercel Deployment - latest:** [https://bracco-hnrbo0blt-datacite.vercel.app/](https://bracco-hnrbo0blt-datacite.vercel.app/)

**Vercel Deployment - with review comments round 1:** [https://bracco-mft35bhdg-datacite.vercel.app/](https://bracco-mft35bhdg-datacite.vercel.app/)

**Definition of Done** - [https://github.com/datacite/tasks/issues/108](https://github.com/datacite/tasks/issues/108)

**Deployment ToDo**

- [x]  ADR for Lupo change for title sorting.
    - https://github.com/datacite/adr/blob/main/doc/adr/0001-primary-title-attribute-added-to-lupo-doi-model-to-enable-sorting-sorting-by-first-title.md
- [x]  Deploy lupo mods that have been added to enable the bracco implementation to production and test.
- [x]  Re-index dois in production and test
- [x]  Coordinate deployment schedule with Kristian - after documentation/blog/announcement.
- [x]  Deploy bracco to production Vercel using version tag "4.0.0".

**Comment by sarala** [comment]
Link to feature: https://datacite.productboard.com/feature-board/planning/features/7104555
