### ISSUE TITLE
Fabrica Software Upgrade

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1603]
LATEST VERCEL PREVIEW: https://bracco-2dvm1e8if-datacite.vercel.app/ (2023/03/06)

**UPDATE (2022-03-03):**

A number of observed issues have been resolved.  Those were documented in [PR#711](https://github.com/datacite/bracco/pull/711)

Waiting on 2nd round of core functionality manual testing and approval by reviewers.

**UPDATE (2022-12-16):**

This task was started in  Tech Debt Week Q4 2022.  There is a Fabrica, Ember v3.16/Node V14 update waiting to be deployed.

I am using this epic to help track the issues related to Fabrica upgrade as this is an ongoing task. 

Pre-deployment tasks: 

Tasks for after deployment of the Ember v3.16 Fabrica:

- [x] clean up.  There are numerous github issues that should be closed and unused branches that should be deleted.
- [ ] Upgrade Fabrica to use Node v16
- [ ] Upgrade Fabrica to through the next few LTS releases (3.20, 3.24, perhaps 3.28)
- [ ] Decide whether to pursue a new framework or to stick with ember and detail the work it would take to go from Ember v3.28 (classic) to Ember v4 and beyond (octane)

- [X]upgrade to use latest main.

**ORIGINAL:**
Upgrading the Fabrica Ember.js framework.  Using this epic to centralize issues and documentation for this task.  This will probably take more than one Tech Debt Week to do so we will try to create goals that can be achieved within this week that will move the task forward and allow us to pick it up again for the next technical debt week.

RESOURCES:

- [Fabrica Software Upgrade Document](https://docs.google.com/document/d/1OWvkvF2jJaVXGE2d6oyiCjZKceWF1EFNRNKuIzcD6RA/edit?usp=sharing)

CHECKLIST FOR THE WEEK:
