### ISSUE TITLE
Modify service front ends to use assets.datacite.org

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1797]
Modify all service front ends to pull assets from assets.datacite.org.  This includes making sure that the correct environments are used (stage, test, production), the environment variables (CDN_URL) point at the correct environment, hard-coded references use environment variables so they can be configured, etc.

- [x] Akita(commons.datacite.org) (issue datacite/akita#263)
- [x] Blog.datacite.org - included with the home page redesign.
- [x] Dackel (repositoryfinder.datacite.org) - Being retired June 1 - before the new home page launch.
- [x] Bracco (doi.datacite.org) (issue datacite/bracco#731)
- [x] OAIP (datacite.org/oaipmh.html) - Repository is retired.
- [x] Schema (schema.datacite.org) (issue datacite/schema#126)
- [x] Search (search.datacite.org) - Being retired June 1 - before the new home page launch
- [x] Stats-portal (stats.datacite.org) (issue datacite/stats-portal#81)
- [x] Volpino (profiles.datacite.org) (Issue https://github.com/datacite/volpino/pull/141)
- [x] lupo - a non-issue.  This [search](https://github.com/search?q=repo%3Adatacite%2Flupo%20CDN_URL&type=code) shows that it already references assets.datacite.org, although I don't think it is ever used.
- [x] mastino - most references to CDN_URL are unused.  There is only one for volpino that needs modification.  See datacite/datacite#1800

**Comment by svogt0511** [comment]
Modify all service front ends to pull assets from assets.datacite.org.  This includes making sure that the correct environments are used (stage, test, production), the environment variables (CDN_URL) point at the correct environment, hard-coded references use environment variables so they can be configured, etc.
