### ISSUE TITLE
Fix service front end links to home page content

### ISSUE THREAD

**Issue by svogt0511** [datacite/datacite#1798]
Links to resources in the current home page might change due to implementation of the new home page.  Service front ends, listed below, have links to these resources.  

The current plan is for the new home page to implement redirects for any links that change, so ultimately, there should be nothing to do with these sites, except maybe to spot check the sites listed below.  

**WAITING ON**
The new home page release.  Then spot check links.  Then close this issue.

- [x] Akita(commons.datacite.org)(issue datacite/akita#262)
- [x]  Blog.datacite.org - included with the home page redesign.
- [x]  Dackel (repositoryfinder.datacite.org) - Being retired June 1 - before the new home page launch.
- [x]  Bracco (doi.datacite.org) (issue datacite/bracco#732)
- [x] OAIP (datacite.org/oaipmh.html) - Repository is retired.
- [x] Schema (schema.datacite.org) (issue datacite/schema#126)
- [x] Search (search.datacite.org) - Being retired June 1 - before the new home page launch
- [x] Stats-portal (stats.datacite.org) (issue datacite/stats-portal#80)
- [x] Volpino (profiles.datacite.org) (Issue datacite/volpino#139)
